### ISSUE TITLE
Tx.checkPreimageOpt raise SCRIPT_ERR_SIG_DER_INVALID_FORMAT exception

### ISSUE THREAD

**Issue by baryon** [scrypt-sv/boilerplate#22]
The exception was randomly raise.

reproduce steps:

1. fix tokenUtxo.scrypt, replace all `Tx.checkPreimage` to `Tx.checkPreimageOpt`

1. run test tokenUtxo.scrypttest.js
```
% npm run single-test tests/js/tokenUtxo.scrypttest.js

> scrypt_boilerplate@0.2.0 single-test /xxx/boilerplate-master
> mocha -r ts-node/register --reporter spec --timeout 120000 "tests/js/tokenUtxo.scrypttest.js"



  Test sCrypt contract UTXO Token In Javascript
Compiling contract /xxx/boilerplate-master/contracts/tokenUtxo.scrypt ...
    1) should succeed when one token is split into two
    2) should succeed when two tokens are merged
    ✓ should succeed when one token UTXO is burnt (127ms)


  1 passing (6s)
  2 failing

  1) Test sCrypt contract UTXO Token In Javascript
       should succeed when one token is split into two:

      SCRIPT_ERR_SIG_DER_INVALID_FORMAT
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (tests/js/tokenUtxo.scrypttest.js:72:47)
      at processImmediate (internal/timers.js:456:21)

  2) Test sCrypt contract UTXO Token In Javascript
       should succeed when two tokens are merged:

      SCRIPT_ERR_SIG_DER_INVALID_FORMAT
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (tests/js/tokenUtxo.scrypttest.js:155:47)
      at processImmediate (internal/timers.js:456:21)

```

**Comment by baryon** [comment]
ref: https://xiaohuiliu.medium.com/optimal-op-push-tx-ded54990c76f

```
const MSB_THRESHOLD = 0x7e
const sha256d = bsv.crypto.Hash.sha256sha256

const changTxForMSB = function (tx_, inputLockingScriptASM, inputAmount, inputIndex, sighashType) {
  for (let i = 0; ; i++) {
  // malleate tx and thus sighash to satisfy constraint
    tx_.nLockTime = i
    const preimage_ = getPreimage(tx_, inputLockingScriptASM, inputAmount, inputIndex, sighashType)
    const preimage = toHex(preimage_)
    const h = sha256d(Buffer.from(preimage, 'hex'))
    const msb = h.readUInt8()
    if (msb < MSB_THRESHOLD) {
      // the resulting MSB of sighash must be less than the threshold
      break
    }
  }
}

```
