### ISSUE TITLE
All tests fail for various reasons on Windows

### ISSUE THREAD

**Issue by hugobuddel** [scrypt-sv/boilerplate#5]
running `npm test` fails with various errors:
```
> git clone git@github.com:scrypt-sv/boilerplate.git

Cloning into 'boilerplate'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 451 (delta 22), reused 28 (delta 11), pack-reused 406 eceiving objects:  97% (438/451)
Receiving objects: 100% (451/451), 208.40 KiB | 833.00 KiB/s, done.
Resolving deltas: 100% (253/253), done.


> cd boilerplate

> npm install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\mocha\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 603 packages from 871 contributors and audited 609 packages in 22.948s

18 packages are looking for funding
  run `npm fund` for details

found 14 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details


> npm test

> scrypt_boilerplate@0.1.0 test C:\[...]\boilerplate
> mocha -r ts-node/register tests/**/*scrypttest.*  --reporter spec --timeout 120000

  Test sCrypt contract Ackermann In Javascript
    1) "before all" hook for "should return true"

  Test sCrypt contract Counter In Javascript
    2) "before all" hook for "should succeed when pushing right preimage & amount"

[...]

  0 passing (15s)
  12 failing

  1) Test sCrypt contract Ackermann In Javascript
       "before all" hook for "should return true":
     Error: Compilation error: ENOENT
      at compile (node_modules\scrypttest\dist\local.js:147:15)
      at buildContractClass (node_modules\scrypttest\dist\local.js:59:17)
      at Context.<anonymous> (tests\js\ackermann.scrypttest.js:9:23)
      at processImmediate (internal/timers.js:439:21)

  2) Test sCrypt contract Counter In Javascript
       "before all" hook for "should succeed when pushing right preimage & amount":
     Error: Compilation error: Error: Compilation fails: Error:
Syntax error: C:\[...]\boilerplate\contracts\advancedCounter.scrypt:1:8:
  |
1 | import "util.scrypt";
  |        ^
File not found: util.scrypt

      at compile (node_modules\scrypttest\dist\local.js:147:15)
      at buildContractClass (node_modules\scrypttest\dist\local.js:59:17)
      at Context.<anonymous> (tests\js\advancedCounter.scrypttest.js:30:21)
      at processImmediate (internal/timers.js:439:21)

[...]

npm ERR! Test failed.  See above for more details.


> npm --version

6.13.4
```

Some notes:
* util.scrypt is there, but also the VSCode plugin complains that "Imported file util.scrypt does not existscrypt"
* Commenting out the catch/throw block in `node_modules\scrypttest\dist\local.js:147:15` shows that all the compilation errors are like this `Error: ENOENT: no such file or directory, open 'p2pkh_asm.json'`

I'm new to VSCode, npm, and sCrypt, so I'm out of my league here. My guess would be that some path is not set correctly somewhere.

Perhaps running windows is the problem? I expected VSCode to only work on Windows, but apparently it should work on Linux too, which is my normal development environment.

**Comment by xhliu** [comment]
This was supposed to be fixed 3 days ago and only a problem on Windows. Pull the latest and try again. Please reopen if it's not fixed.

VSCode works on Windows, Linux, and Mac OS.

**Comment by hugobuddel** [comment]
I've just retried (with npm 6.14.5 this time), and the tests still failed. Recloned the repository in a new directory. (The first time I tried was just before posting the issue though.)

It seems I don't have permission to reopen the issue. I also don't have access to the slack, is it possible to get that?

All tests indeed run fine on Linux (Fedora something), so I'm happy to use that.

**Comment by xhliu** [comment]
Join [slack](https://scryptdoc.readthedocs.io/en/latest/#contact) here.

**Comment by xhliu** [comment]
Should have been fixed in newer version.
